### ISSUE TITLE
Modal is breaking layout

### ISSUE THREAD

**Issue by murbanowicz** [Morgul/vueboot#2]
Everything is going to the left when modal is open.
Visible on your demo page.

**Comment by Morgul** [comment]
This was a bug with the first Bootstrap v4 alpha: https://github.com/twbs/bootstrap/issues/17399. This is fixed in Bootstrap `v4.0.0-alpha.2`.

I haven't updated the github pages branch for the demo page to alpha 2 yet, since there hasn't been any code changes in vueboot. I will attempt to do that in the near future, so the demo doesn't demonstrate a bug that's already been fixed.

**Comment by Morgul** [comment]
This has been fixed on the main site.
