### ISSUE TITLE
When using import, I got warning that vueboot.js is prebuilt

### ISSUE THREAD

**Issue by leapon** [Morgul/vueboot#4]
```
import { tabset, tab  } from 'vueboot'


WARNING in ./~/vueboot/dist/vueboot.js
Critical dependencies:
2:480-487 This seems to be a pre-built javascript file.
```

Is there a way to get round this? Thanks.

**Comment by Morgul** [comment]
I'm unfamiliar with this warning, but some searching seems to point towards this being a webpack warning. From what I can tell, webpack prefers you use the source and let webpack compile it, rather than using pre-built files.

The problem is, vueboot uses babel and vueify. If you want to compile it yourself, you will need to do a lot of work rebuilding the toolchain that vueboot uses. _Personally_ I don't see how that could be worth the effort, but the webpack guys seem to disagree.

To do this, I am thinking you need to use `'vueboot/src/vueboot'` as the entry point, and then look around to figure out how to make webpack compile `.vue` files.

If you figure out how to get it to work, please report back and I'll update the docs to include a section on webpack. But, as this is just a warning, I don't feel a strong need to make any modifications to vueboot to make it more webpack friendly. (But, I will listen to suggestions, if you have any.)

**Comment by leapon** [comment]
@Morgul You are correct that I am using webpack. However I don't have babel and vueify in the webpack build process. 

Here is my webpack config file:
https://github.com/leapon/vue-test/blob/master/webpack.config.js

I can build from source with vuestrap and other vue components, however vueboot is not working with build from source. Looks like it is the build dependency differences. I will report back if I have time to figure this out. I am relatively new to vue so I am more in testing and exploring mode at the moment.

well, I do have babel in my webpack. Maybe I just need to add vueify somewhere to get it click.

**Comment by leapon** [comment]
Not an issue anymore. Maybe a feature request to be able to build with webpack from source.
